version: '3.8'

services:
  postgres:
   image: postgres:15
   container_name: letscode_build
   environment:
      POSTGRES_DB: letscode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
   ports:
    - "5433:5432"
   volumes:
    - letscode_db_data:/var/lib/postgresql/data
   restart: unless-stopped

volumes:
  letscode_db_data:
